# 판다스(pandas)
- 시리즈
- 데이터프레임

In [33]:
# pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.1.1)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd
data1 = np.arange(3,9)
data1

# 1차 원적
data2 = pd.Series(data1)
print(data2, type(data2), data2.index, data2.values, data2.dtype)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=6, step=1) [3 4 5 6 7 8] int64

In [6]:
# 판다스 시리즈의 데이터 타입 
data3 = pd.Series([11,22,33,44,55], dtype='float')
print(data3)

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
dtype: float64

In [8]:
data4 = pd.Series([44,55,66,77,88], index=['aa','bb','cc','dd','ee'])
print(data4)

aa    44
bb    55
cc    66
dd    77
ee    88
dtype: int64

In [6]:
# 판다스 시리즈 딕셔너리데이터

population_dict = {
    'korea': 5182,
    'japen': 12622,
    'china': 141178,
    'usa': 32976
}
# population_dict.keys()
# population_dict.values()
# population_dict.items()

country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근방법
print(country.loc['usa'])
print(country.iloc[3])

korea      5182
japen     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japen', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
32976
32976

In [7]:
population_dict = {
    'korea': 5182,
    'japen': 12622,
    'china': 141178,
    'usa': 32976
}
GDP_dict = {
    'korea': 169320000,
    'japen': 516700000,
    'china': 140925000,
    'usa' : 204128000
}

pup = pd.Series(population_dict)
GDP = pd.Series(GDP_dict)
country = pd.DataFrame({"population":pup,'GDP':GDP})
country.index.name = "Country"
country.columns.name = "Info"
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)

Index(['korea', 'japen', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'GDP'], dtype='object', name='Info')
[[     5182 169320000]
 [    12622 516700000]
 [   141178 140925000]
 [    32976 204128000]] (4, 2) 8 2

In [8]:
country.loc['korea'], country.loc['usa']
country.iloc[2], country.iloc[1]

(Info
 population       141178
 GDP           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 GDP           516700000
 Name: japen, dtype: int64)

In [9]:
country.loc['korea':'japen']    #   <= x <=

Info     population        GDP
Country
korea          5182  169320000
japen         12622  516700000

In [10]:
country.iloc[0:2]    #   <= x <

Info     population        GDP
Country
korea          5182  169320000
japen         12622  516700000

In [11]:
country

Info     population        GDP
Country
korea          5182  169320000
japen         12622  516700000
china        141178  140925000
usa           32976  204128000

In [12]:
# 컬럼추가
# country['what?'] = [11,22,33,44]
per = country['GDP']/country['population']
country['GDP_per'] = per

In [13]:
country

Info     population        GDP       GDP_per
Country
korea          5182  169320000  32674.642995
japen         12622  516700000  40936.460149
china        141178  140925000    998.207936
usa           32976  204128000   6190.198933

In [25]:
# 컬럼삭제
country = country.drop('what?', axis=1, errors='ignore')

In [26]:
country

Info     population        GDP
Country
japen         12622  516700000
usa           32976  204128000

In [32]:
# 과일별 가격 (원)
price = {
"Apple": 1200,
"Banana": 800,
"Orange": 1500,
"Mango": 2500
}

# 과일별 갯수
quan = {
"Apple": 10,
"Banana": 5,
"Orange": 7,
"Mango": 20
}

# 위 내용을 이용하여 데이터 프레임으로 만들고 마지막컬럼은 행의 토탈가격을 붙여라.
fruit = pd.DataFrame({'price':price,'quan':quan})
fruit['won'] = fruit['price'] * fruit['quan']

# 행추가 방법1
fruit.loc['kiwi'] = [800, 11, np.nan ]
fruit.loc['kiwi','won'] = fruit.loc['kiwi','price'] * fruit.loc['kiwi','quan']

# 행추가 방법2
melon = pd.Series( data=[4500, 6, 4500 * 6], index=['price','quan','won'])
fruit.loc['melon'] = melon
fruit

# 행추가 해서 결측값 확인하기
fruit.loc['lemon'] = [200, np.nan , np.nan]
fruit.isnull() #.sum() 개수를 파악할 때

# NaN 값이 있는 행을 찾는 방법 1
fruit[fruit['won'].isnull()].index

# NaN 값이 있는 행을 찾는 방법 2
# fruit[ax.any(axis=1)].index

# 삭제 fruit.drop( 위에서 찾은 인덱스 넣어주면 됨.)

Index(['lemon'], dtype='object')

In [34]:
# 과일별 가격 (원)
import pandas as pd
import numpy as np

price = {
"Apple": 1200,
"Banana": 800,
"Orange": 1500,
"Mango": 2500
}

# 과일별 갯수
quan = {
"Apple": 10,
"Banana": 5,
"Orange": 7,
"Mango": 20
}

# 위 내용을 이용하여 데이터 프레임으로 만들고 마지막컬럼은 행의 토탈가격을 붙여라.
fruit = pd.DataFrame({'price':price,'quan':quan})
fruit['won'] = fruit['price'] * fruit['quan']

# 행추가 방법1
fruit.loc['kiwi'] = [800, 11, np.nan ]
fruit.loc['kiwi','won'] = fruit.loc['kiwi','price'] * fruit.loc['kiwi','quan']

# 행추가 방법2
melon = pd.Series( data=[4500, 6, 4500 * 6], index=['price','quan','won'])
fruit.loc['melon'] = melon
fruit

# 행추가 해서 결측값 확인하기
fruit.loc['lemon'] = [200, np.nan , np.nan]
fruit.isnull() #.sum() 개수를 파악할 때

# NaN 값이 있는 행을 찾는 방법 1
fruit[fruit['won'].isnull()].index

# NaN 값이 있는 행을 찾는 방법 2
# fruit[ax.any(axis=1)].index

# 삭제 fruit.drop( 위에서 찾은 인덱스 넣어주면 됨.)

Index(['lemon'], dtype='object')

In [29]:
country

Info     population        GDP
Country
japen         12622  516700000
usa           32976  204128000

In [30]:
country[country['population'] > 30000]

Info     population        GDP
Country
usa           32976  204128000

In [31]:
f = (country['population'] > 6000 ) & (country['population'] < 100000 )

# 원하는 컬럼 선택 1
country = country.loc[f, ['population', 'GDP']]

# 원하는 컬럼 선택 2

country.loc['japen':'japen', 'population':'GDP']

Info     population        GDP
Country
japen         12622  516700000

In [36]:
# 방법1 일반적인
data = {
    '이름':['홍길동','박철수','김영희'],
    '국어':[80,60,70],
    '수학':[70,70,90],
    '영어':[80,80,80]
}
df = pd.DataFrame(data)
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [37]:
# 방법2 키값 쌍으로 리스트에 저장
data = [
    {'이름':'홍길동','국어':80,'수학':70,'영어':80},
    {'이름':'박철수','국어':60,'수학':70,'영어':80},
    {'이름':'김영희','국어':70,'수학':90,'영어':80},
]
df = pd.DataFrame(data)
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [174]:
# 방법3 리스트에 튜플로
data = [
    ('홍길동',80,70,80),
    ('박철수',60,70,80),
    ('김영희',70,90,80),
]
df = pd.DataFrame(data, columns=['이름','국어','수학','영어'])
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [49]:
# 방법4 np를 사용한 df
import numpy as np
data0 = [['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80]]

data = np.array(data0)
df = pd.DataFrame(data, columns=['이름','국어','수학','영어'])
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

# 판다스(pandas) 심화

## 데이터프레임 정렬

In [195]:
import numpy as np
import pandas as pd
print("DdataFrame: ")
data = {
    'col1':[2,1,9,8,7,4],
    'col2':['A','A','B', np.nan, 'D','C'],
    'col3':[0,1,9,4,2,3],
}
index = [1,3,2,5,0,4]
df = pd.DataFrame(data, index=index)
df

DdataFrame:

   col1 col2  col3
1     2    A     0
3     1    A     1
2     9    B     9
5     8  NaN     4
0     7    D     2
4     4    C     3

In [196]:
df = df.sort_index(axis=0) # 행을 축으로 정렬
df

   col1 col2  col3
0     7    D     2
1     2    A     0
2     9    B     9
3     1    A     1
4     4    C     3
5     8  NaN     4

In [197]:
df.sort_index(axis=1, ascending=False) # 열을 축으로 정렬, 내림차순

   col3 col2  col1
0     2    D     7
1     0    A     2
2     9    B     9
3     1    A     1
4     3    C     4
5     4  NaN     8

In [198]:
df.sort_values('col1', ascending=False) # values 를 기준으로 정렬

   col1 col2  col3
2     9    B     9
5     8  NaN     4
0     7    D     2
4     4    C     3
1     2    A     0
3     1    A     1

In [199]:
df.sort_values(['col2','col1'], ascending=[True, False]) # values 를 기준으로 이동

   col1 col2  col3
1     2    A     0
3     1    A     1
2     9    B     9
4     4    C     3
0     7    D     2
5     8  NaN     4

## 데이터 분석용 함수

In [10]:
import numpy as np
import pandas as pd
data ={
    'korean': [50,60,70,30],
    'math':[30,np.nan,40,20],
}
index = ['홍길순','수퍼걸','쉬헐크','배트걸']
df = pd.DataFrame(data, index=index)
print(df.index)
print(df.columns)
df

Index(['홍길순', '수퍼걸', '쉬헐크', '배트걸'], dtype='object')
Index(['korean', 'math'], dtype='object')

     korean  math
홍길순      50  30.0
수퍼걸      60   NaN
쉬헐크      70  40.0
배트걸      30  20.0

In [11]:
# count 함수
print(df.count())
print(df.count(axis=1))

korean    4
math      3
dtype: int64
홍길순    2
수퍼걸    1
쉬헐크    2
배트걸    2
dtype: int64

In [12]:
# max() 함수
print(df.max(axis=0))
print(df.max(axis=1))

korean    70.0
math      40.0
dtype: float64
홍길순    50.0
수퍼걸    60.0
쉬헐크    70.0
배트걸    30.0
dtype: float64

In [13]:
# min() 함수
print(df.min(axis=0))
print(df.min(axis=1))

korean    30.0
math      20.0
dtype: float64
홍길순    30.0
수퍼걸    60.0
쉬헐크    40.0
배트걸    20.0
dtype: float64

In [14]:
# sum() 함수
print(df.sum(axis=0))
print(df.sum(axis=1))

korean    210.0
math       90.0
dtype: float64
홍길순     80.0
수퍼걸     60.0
쉬헐크    110.0
배트걸     50.0
dtype: float64

In [15]:
# mean() 함수
print(df.mean(axis=0))
print(df.mean(axis=1))
print(df.mean(axis=1, skipna=False))
data1 = df.mean(axis=1, skipna=False)
print(data1[~data1.isnull()])
print(data1[data1.notnull()])

korean    52.5
math      30.0
dtype: float64
홍길순    40.0
수퍼걸    60.0
쉬헐크    55.0
배트걸    25.0
dtype: float64
홍길순    40.0
수퍼걸     NaN
쉬헐크    55.0
배트걸    25.0
dtype: float64
홍길순    40.0
쉬헐크    55.0
배트걸    25.0
dtype: float64
홍길순    40.0
쉬헐크    55.0
배트걸    25.0
dtype: float64

In [16]:
# df['math'].mean()
df['math'] = df['math'].fillna(df['math'].mean())
df

     korean  math
홍길순      50  30.0
수퍼걸      60  30.0
쉬헐크      70  40.0
배트걸      30  20.0

## 그룹으로 묶기 (groupby)

In [6]:
import numpy as np
import pandas as pd
df = pd.DataFrame({
    'key'    : ['A', 'A', 'A', 'A', 'B', 'C'],
    'data1':[1,2,3,1,2,3],
    'data2':[4,4,6,0,6,1],
    })
print("DataFrame")
df

DataFrame

  key  data1  data2
0   A      1      4
1   A      2      4
2   A      3      6
3   A      1      0
4   B      2      6
5   C      3      1

In [7]:
df.groupby('key').sum()

     data1  data2
key
A        7     14
B        2      6
C        3      1

In [8]:
df.groupby(['key','data1']).sum().reset_index()

  key  data1  data2
0   A      1      4
1   A      2      4
2   A      3      6
3   B      2      6
4   C      3      1

In [9]:
df.groupby('key').mean()

     data1  data2
key
A     1.75    3.5
B     2.00    6.0
C     3.00    1.0

In [24]:
def filter_mean(x):
    return x['data2'].mean() < 3
df.groupby('key').filter(filter_mean)
# filter_mean(df.groupby('key'))

  key  data1  data2
5   C      3      1

In [18]:
df.groupby('key').aggregate(['min','median','max'])

    data1            data2
      min median max   min median max
key
A       1    1.5   3     0    4.0   6
B       2    2.0   2     6    6.0   6
C       3    3.0   3     1    1.0   1

In [20]:
df.groupby('key').aggregate({'data1':'mean','data2':'sum'})

     data1  data2
key
A     1.75     14
B     2.00      6
C     3.00      1

### 피봇과 피봇 테이블

In [26]:
import pandas as pd

df = pd.DataFrame([
    ['20210901', 'A', 1],
    ['20210901', 'B', 10],
    ['20210901', 'C', 100],
    ['20210902', 'A', 2],
    ['20210902', 'B', 20],
    ['20210902', 'C', 200],
    ['20210903', 'A', 3],
    ['20210903', 'B', 30],
    ['20210903', 'C', 300],
], columns = ['date','type', 'volume'])
df

       date type  volume
0  20210901    A       1
1  20210901    B      10
2  20210901    C     100
3  20210902    A       2
4  20210902    B      20
5  20210902    C     200
6  20210903    A       3
7  20210903    B      30
8  20210903    C     300

In [29]:
pv1 = df.pivot(index="date", columns="type", values = "volume")
pv1

type      A   B    C
date
20210901  1  10  100
20210902  2  20  200
20210903  3  30  300

In [37]:
pv1_idx = pv1.reset_index()
pv1_idx

type      date  A   B    C
0     20210901  1  10  100
1     20210902  2  20  200
2     20210903  3  30  300

In [39]:
pv1_idx.set_index('date')

type      A   B    C
date
20210901  1  10  100
20210902  2  20  200
20210903  3  30  300

# 문제2
- 박철수의 국어와, 수학점수만 출력하라
# 문제3
- 수학이 80이상인 사람 모든 행을 출력하라.
# 문제4
- 모든 과목의 평균 점수를 마지막 컬럼에 넣고 "평균"이라는 컬럼명을 써라.
# 문제5
- 전학온 학생을 추가하라 ,
- (신지능 85, 95, 50)
# 문제6
- 전학온 학생2 지만 수학시험을 안친 상태로 등록하라.
- (최자바 90,X, 85)

In [61]:
# 문제 2 - Only 박철수만 출력하기 
import numpy as np
data0 = [['박철수',60,70]]

data = np.array(data0)
df = pd.DataFrame(data, columns=['이름','국어','수학'])
df

    이름  국어  수학
0  박철수  60  70

In [200]:
# 문제 3 - 수학이 80 이상인 사람 모든 행 출력하기
import numpy as np
import pandas as pd  # pd를 사용하려면 pandas 임포트가 필요합니다.

data0 = [['홍길동', 80, 70, 80], ['박철수', 60, 70, 80], ['김영희', 70, 90, 80]]

# DataFrame을 만들 때 numpy 배열을 거치지 않고 바로 넣는 것이 좋습니다.
df = pd.DataFrame(data0, columns=['이름', '국어', '수학', '영어'])

# 데이터 타입을 숫자로 변환 (수학 컬럼을 비교하기 위함)
df['수학'] = df['수학'].astype(int)

# 수학 점수가 80점 이상인 행 필터링
result = df[df['수학'] >= 80]
result

    이름  국어  수학  영어
2  김영희  70  90  80

In [187]:
# 문제 4 - 마지막 컬럼에 평균 넣기
import numpy as np
import pandas as pd  # pandas 임포트 확인

data0 = [['홍길동', 80, 70, 80], ['박철수', 60, 70, 80], ['김영희', 70, 90, 80]]

# DataFrame 생성 (숫자 계산을 위해 바로 data0를 넣는 것을 권장합니다)
df = pd.DataFrame(data0, columns=['이름', '국어', '수학', '영어'])

# 1. 국어, 수학, 영어 컬럼을 숫자(int) 타입으로 변환
df[['국어', '수학', '영어']] = df[['국어', '수학', '영어']].astype(int)

# 2. 행(Row) 방향으로 평균을 구해 '평균'이라는 새로운 컬럼에 대입
df['평균'] = df[['국어', '수학', '영어']].mean(axis=1)

df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [114]:
# 문제 5
import numpy as np
data0 = [['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80],['신지능',85,95,50]]

data = np.array(data0)
df = pd.DataFrame(data, columns=['이름','국어','수학','영어'])
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80
3  신지능  85  95  50

In [75]:
# 문제 6
import numpy as np
data0 = [['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80],['신지능',85,95,50],['최자바',85,"X",50]]

data = np.array(data0)
df = pd.DataFrame(data, columns=['이름','국어','수학','영어'])
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80
3  신지능  85  95  50
4  최자바  85   X  50